# This is a basic workflow to help you get started with Actions

name: Hexo deploy workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      # 检查node版本
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      # 执行hexo generate命令
      - name: Act hexo generate
        run: |
          rm -rf ./node_modules && npm ci && npm run build
        
      # 检查文件夹
      - name: Check folder
        run: |
          cd public && ls && cd ../

      # 部署
      - name: Act github.io hexo deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY || secrets.DEPENDABOT_KEY }}
          publish_branch: gh-pages
          publish_dir: public
          enable_jekyll: true
          force_orphan: true

      - name: Act blog.meglody.com hexo deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'ubuntu'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './public/*'  # 对应我们项目build的文件夹路径
          remote_path: '/home/ubuntu/docker-source-file/blog'
